language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mongo db_test --eval 'db.addUser("travis", "test");'
  - cd hub
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - composer phplint
  - composer test
  - composer behat
  - CODECLIMATE_REPO_TOKEN=a7a5144310e22363bc8314482209e3478e2d55b85cea9a6fcf3fb2b24df091f8 php vendor/codeclimate/php-test-reporter/composer/bin/test-reporter

matrix:
  fast_finish: true
  allow_failures:
      - php: 5.4

notifications:
  email:
    recipients:
      - apietka@future-processing.com
      - team.mvp@future-processing.com
    on_success: change
    on_failure: always
  webhooks: http://morning-escarpment-1297.herokuapp.com/travis

env:
  - MONGO_DB_USER=travis MONGO_DB_PASSWORD=test MONGO_DB_PORT=27017 MONGO_DB_URL=127.0.0.1 MONGO_DB_NAME=db_test
