server:
  build: ./run/docker/server
  volumes:
   - "./:/data/larmo-server/"
   - .:/app
   - ./:/app2/
   - ./api/:/app3/
  environment:
   - MONGO_DB_URL=mongo
   - MONGO_DB_NAME=larmo-server
   - MONGO_DB_PORT=27017
 # links:
 #  - mongo

# mongo:
#  image: mongo
#  volumes:
#   - "./run/docker/mongo/data:/data/db"
#  ports:
#    - "27018:27017"