hub:
  build: ./run/docker/server
  ports:
   - "5100:80"
  volumes:
   - .:/data/larmo-server/
  environment:
   - MONGO_DB_URL=mongo
   - MONGO_DB_NAME=hubtest
   - MONGO_DB_PORT=27017
  links:
   - mongo

mongo:
  image: mongo
  volumes:
   - ./run/docker/mongo/data:/data/db
  ports:
    - "27018:27017"