hub:
  build: hub
  ports:
   - "8181:80"
  volumes:
   - ../hub:/data/larmo-hub/
  environment:
   - MONGO_DB_URL=mongo
   - MONGO_DB_NAME=larmo-server
   - MONGO_DB_PORT=27017
  links:
   - mongo

mongo:
  image: mongo
  volumes:
   - ./mongo/data:/data/db
  ports:
    - "27018:27017"